@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmNDAzZWNkNDA5NWZhMGZlZjZhZGMiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJHVLUk1sUkt2MDRLZ0VzaVFsUmVjZE9Oa21hb2IvN1hYWWxhdTFhZnRFZ3BCeTlmR3BYWWF5IiwiZGF0ZU9mQmlydGgiOiIyMDI0LTA3LTExVDAyOjE1OjI2LjgxMloiLCJpbWFnZSI6ImRlZmF1bHQvcHJvZmlsZS5wbmciLCJhZGRyZXNzIjoiYXNkIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwiX192IjowLCJpYXQiOjE3MjExMzY3MjMsImV4cCI6MTcyMTE0MDMyM30.KGQ7iKt1824uNTsSl-qbe2nwfe7hWDPPJ9FiIgAKzyg
@id=66933416d058e02505bf922d
GET http://localhost:5000/api/memberships
Authorization:  Bearer {{token}}
###
POST http://localhost:5000/api/memberships
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name" : "Paket siang",
    "price" : 2,
    "description" : "Latihan 2 minggu",
    "duration" : 30
}
###
GET http://localhost:5000/api/memberships/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

###
PUT http://localhost:5000/api/memberships/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name" : "Paket malam"
}

### 
DELETE http://localhost:5000/api/memberships/{{id}}
Authorization: Bearer {{token}}

### 
POST http://localhost:5000/api/memberships/publish/{{id}}
Authorization: Bearer {{token}}

###
POST http://localhost:5000/api/memberships/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njk1ZDMwZjRmZGQ5ZDk5MDlhYzE0YzkiLCJuYW1lIjoiQnVyaGFuIiwiZW1haWwiOiJyaXphbEByaXphbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRYaDV0TFRpTVRURy5DMUhHemNJeThlSGV5YzhqYU5CS3FsOVp5eWFFZkQ3TUJSRmhYR2VhMiIsImRhdGVPZkJpcnRoIjoiMjAwNS0wNy0yMlQwMDowMDowMC4wMDBaIiwiZ2VuZGVyIjoibWFsZSIsImltYWdlIjoiZGVmYXVsdC9wcm9maWxlLnBuZyIsImFkZHJlc3MiOiJTdWthYnVtaSBDaXR5Iiwicm9sZSI6Im1lbWJlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDE6NTU6MjcuMTI2WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMTZUMTM6MTg6MzEuMDQyWiIsIl9fdiI6MCwiaWF0IjoxNzIxMTM2Nzc1LCJleHAiOjE3MjExNDAzNzV9.2RjeXJ8tl8m5wU4R66jj3I7W-8_62qv5DI2XYnq7zeo
Content-Type: application/json

{
    "membershipId" : "66933416d058e02505bf922d"
}