# Get user profile data
# 1. Member
# 2. Admin
# 3. Employee
GET http://localhost:5000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg0ZDEzY2MyZTRkNjQwN2Q5ZjYwMmYiLCJuYW1lIjoiUml6YWwgQnVyaGFudWRpbiIsImVtYWlsIjoicml6YWxidXJoYW51ZGluNTU2QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDR0U0pYb0F4Rkd4OTN0RTAvNGhNM2VXZHJmbkVEQkJNSFg3eXFVLk9kWllab2ZWV0l5OC9DIiwiZGF0ZU9mQmlydGgiOiIyMDA1LTA3LTIyVDAwOjAwOjAwLjAwMFoiLCJnZW5kZXIiOiJtYWxlIiwiaW1hZ2UiOiJpbWFnZXMvZGVmYXVsdC9wcm9maWxlLnBuZyIsImFkZHJlc3MiOiJTdWthYnVtaSBDaXR5Iiwicm9sZSI6Im1lbWJlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDNUMDQ6MTk6MDguMjIzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDNUMDQ6MTk6MDguMjIzWiIsIl9fdiI6MCwiaWF0IjoxNzE5OTgxNzkzLCJleHAiOjE3MTk5ODUzOTN9.tF60qcQtBwI8_SwzLhWyQlrPc9bMgkh8SlrdnHZk39I

###
PUT http://localhost:5000/api/profile
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg0ZDEzY2MyZTRkNjQwN2Q5ZjYwMmYiLCJuYW1lIjoiUml6YWwgQnVyaGFudWRpbiIsImVtYWlsIjoicml6YWxidXJoYW51ZGluNTU2QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJDR0U0pYb0F4Rkd4OTN0RTAvNGhNM2VXZHJmbkVEQkJNSFg3eXFVLk9kWllab2ZWV0l5OC9DIiwiZGF0ZU9mQmlydGgiOiIyMDA1LTA3LTIyVDAwOjAwOjAwLjAwMFoiLCJnZW5kZXIiOiJtYWxlIiwiaW1hZ2UiOiJpbWFnZXMvZGVmYXVsdC9wcm9maWxlLnBuZyIsImFkZHJlc3MiOiJTdWthYnVtaSBDaXR5Iiwicm9sZSI6Im1lbWJlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDNUMDQ6MTk6MDguMjIzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMDNUMDQ6MTk6MDguMjIzWiIsIl9fdiI6MCwiaWF0IjoxNzE5OTgxNzkzLCJleHAiOjE3MTk5ODUzOTN9.tF60qcQtBwI8_SwzLhWyQlrPc9bMgkh8SlrdnHZk39I

{
    "name" : "Burhan"
}

