@id =
GET {{baseUrl}}/memberships
Authorization: Bearer {{token}}
Content-Type: application/json

### GET : get membership
GET {{baseUrl}}/memberships/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

### POST : add membership
POST {{baseUrl}}/memberships
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name" : "",
    "description" : "",
    "price" : 0
}

### PUT : update membership
PUT {{baseUrl}}/memberships/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name" : ""
}

### PATCH : update published
PATCH {{baseUrl}}/memberships/{{id}}/publish
Authorization: Bearer {{token}}
Content-Type: application/json

### DELETE : delete membership
DELETE {{baseUrl}}/memberships/{{id}}
Authorization: Bearer {{token}}