
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg0ZDEzY2MyZTRkNjQwN2Q5ZjYwMmYiLCJuYW1lIjoiQnVyaGFuIiwiZW1haWwiOiJyaXphbGJ1cmhhbnVkaW41NTZAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkNHRTSlhvQXhGR3g5M3RFMC80aE0zZVdkcmZuRURCQk1IWDd5cVUuT2RaWVpvZlZXSXk4L0MiLCJkYXRlT2ZCaXJ0aCI6IjIwMDUtMDctMjJUMDA6MDA6MDAuMDAwWiIsImdlbmRlciI6Im1hbGUiLCJpbWFnZSI6ImltYWdlcy9kZWZhdWx0L3Byb2ZpbGUucG5nIiwiYWRkcmVzcyI6IlN1a2FidW1pIENpdHkiLCJyb2xlIjoibWVtYmVyIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0wM1QwNDoxOTowOC4yMjNaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0wM1QwNTowNDozMS4zMDNaIiwiX192IjowLCJpYXQiOjE3MjAwMDYyMDIsImV4cCI6MTcyMDAwOTgwMn0.TYWr7WS91ngmmyqHOJY8lmKsSKl9iqU4w8ZXhtkQJsw
###
POST http://localhost:5000/api/attendances/check_out
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "code" : "HALOHALOHALOHALO"
}

###
GET http://localhost:5000/api/attendances/code
Authorization: Bearer {{token}}
###
GET http://localhost:5000/api/attendances/seed
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET http://localhost:5000/api/attendances
Content-Type: application/json
Authorization: Bearer {{token}}