
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmNDAzZWNkNDA5NWZhMGZlZjZhZGMiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJHVLUk1sUkt2MDRLZ0VzaVFsUmVjZE9Oa21hb2IvN1hYWWxhdTFhZnRFZ3BCeTlmR3BYWWF5IiwiZGF0ZU9mQmlydGgiOiIyMDI0LTA3LTExVDAyOjE1OjI2LjgxMloiLCJpbWFnZSI6ImRlZmF1bHQvcHJvZmlsZS5wbmciLCJhZGRyZXNzIjoiYXNkIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwiX192IjowLCJpYXQiOjE3MjEzMDUzNTIsImV4cCI6MTcyMTMwODk1Mn0.VUF27usohdt4YFbrM3HAS6ejq5AaB23yfWFLZ8BM27E
POST http://localhost:5000/api/attendances/check_in
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njk1ZDMwZjRmZGQ5ZDk5MDlhYzE0YzkiLCJuYW1lIjoiQnVyaGFuIiwiZW1haWwiOiJyaXphbEByaXphbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRYaDV0TFRpTVRURy5DMUhHemNJeThlSGV5YzhqYU5CS3FsOVp5eWFFZkQ3TUJSRmhYR2VhMiIsImRhdGVPZkJpcnRoIjoiMjAwNS0wNy0yMlQwMDowMDowMC4wMDBaIiwiZ2VuZGVyIjoibWFsZSIsImltYWdlIjoiZGVmYXVsdC9wcm9maWxlLnBuZyIsImFkZHJlc3MiOiJTdWthYnVtaSBDaXR5Iiwicm9sZSI6Im1lbWJlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDE6NTU6MjcuMTI2WiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMTZUMTM6MTg6MzEuMDQyWiIsIl9fdiI6MCwiaWF0IjoxNzIxMzA1Mjk0LCJleHAiOjE3MjEzMDg4OTR9.IZv8YaVkf2Rp4W9BcD5KlXBeD8E0nPCzsmTboQh9IGU

{
    "code" : "OFUEIM"
}

###
GET http://localhost:5000/api/attendances/code
Authorization: Bearer {{token}}
###
GET http://localhost:5000/api/attendances
Content-Type: application/json
Authorization: Bearer {{token}}