
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmNDAzZWNkNDA5NWZhMGZlZjZhZGMiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJHVLUk1sUkt2MDRLZ0VzaVFsUmVjZE9Oa21hb2IvN1hYWWxhdTFhZnRFZ3BCeTlmR3BYWWF5IiwiZGF0ZU9mQmlydGgiOiIyMDI0LTA3LTExVDAyOjE1OjI2LjgxMloiLCJpbWFnZSI6ImRlZmF1bHQvcHJvZmlsZS5wbmciLCJhZGRyZXNzIjoiYXNkIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwiX192IjowLCJpYXQiOjE3MjEwOTM1ODgsImV4cCI6MTcyMTA5NzE4OH0.CTvFRFaCH7OwWKDzDTlEtFs32Vc-n0TnocVkC4bF8bM
###
POST http://localhost:5000/api/attendances/check_out
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njk1ZDMwZjRmZGQ5ZDk5MDlhYzE0YzkiLCJuYW1lIjoiUml6YWwgQnVyaGFudWRpbiIsImVtYWlsIjoicml6YWxAcml6YWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkUFhiLllGMlBoeVJUN3M4c2RsaThuT1gvQS9sVTYvSWpIZG5LWmhHbXhndWt5OFdoRlJLRFMiLCJkYXRlT2ZCaXJ0aCI6IjIwMDUtMDctMjJUMDA6MDA6MDAuMDAwWiIsImdlbmRlciI6Im1hbGUiLCJpbWFnZSI6ImRlZmF1bHQvcHJvZmlsZS5wbmciLCJhZGRyZXNzIjoiU3VrYWJ1bWkgQ2l0eSIsInJvbGUiOiJtZW1iZXIiLCJjcmVhdGVkQXQiOiIyMDI0LTA3LTE2VDAxOjU1OjI3LjEyNloiLCJ1cGRhdGVkQXQiOiIyMDI0LTA3LTE2VDAxOjU1OjI3LjEyNloiLCJfX3YiOjAsImlhdCI6MTcyMTA5NDk4OCwiZXhwIjoxNzIxMDk4NTg4fQ.UJ4u1tkMf7-Zq87HnDsa8ReLJtOyZJVSZaI_8DiiViE

{
    "code" : "QERRBJ"
}

###
GET http://localhost:5000/api/attendances/code
Authorization: Bearer {{token}}
###
GET http://localhost:5000/api/attendances?startDate=2024-07-02&endDate=2024-07-29&memberId=6695d30f4fdd9d9909ac14c9
Content-Type: application/json
Authorization: Bearer {{token}}