@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Njg0ZDEzY2MyZTRkNjQwN2Q5ZjYwMmYiLCJuYW1lIjoiQnVyaGFuIiwiZW1haWwiOiJyaXphbGJ1cmhhbnVkaW41NTZAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkNHRTSlhvQXhGR3g5M3RFMC80aE0zZVdkcmZuRURCQk1IWDd5cVUuT2RaWVpvZlZXSXk4L0MiLCJkYXRlT2ZCaXJ0aCI6IjIwMDUtMDctMjJUMDA6MDA6MDAuMDAwWiIsImdlbmRlciI6Im1hbGUiLCJpbWFnZSI6ImltYWdlcy9wcm9maWxlUGljdHVyZS0xNzIxMDM4NTI1NzU4LmpwZyIsImFkZHJlc3MiOiJTdWthYnVtaSBDaXR5Iiwicm9sZSI6Im1lbWJlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMDNUMDQ6MTk6MDguMjIzWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDctMTVUMTA6MTU6MjUuNzcxWiIsIl9fdiI6MCwiaWF0IjoxNzIxMDkzNDE0LCJleHAiOjE3MjEwOTcwMTR9.eO6p3a-WEvbalOn19o8HHckIvczq5ToAuEQkPUW_uZs
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email" : "admin@admin.com",
    "password" : "password"
}

# {
#     "email" : "rizal@rizal.com",
#     "password" : "halohalo"
# }


###
GET http://localhost:5000/api/seedAdmin

###
GET http://localhost:5000/api/users?role=member
Authorization: Bearer {{token}}