@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjhmNDAzZWNkNDA5NWZhMGZlZjZhZGMiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsInBhc3N3b3JkIjoiJDJhJDEwJHVLUk1sUkt2MDRLZ0VzaVFsUmVjZE9Oa21hb2IvN1hYWWxhdTFhZnRFZ3BCeTlmR3BYWWF5IiwiZGF0ZU9mQmlydGgiOiIyMDI0LTA3LTExVDAyOjE1OjI2LjgxMloiLCJpbWFnZSI6ImRlZmF1bHQvcHJvZmlsZS5wbmciLCJhZGRyZXNzIjoiYXNkIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwidXBkYXRlZEF0IjoiMjAyNC0wNy0xMVQwMjoxNToyNi44MjlaIiwiX192IjowLCJpYXQiOjE3MjEzMTU4MzQsImV4cCI6MTcyMTMxOTQzNH0.J0qw9VNTtgs0yFKiqr8B9u87UctgQMyOY68ZLr_2wZ4
GET http://localhost:5000/api/classes
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST http://localhost:5000/api/classes
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name" :"Class gym",
    "description" : "Latihan dalam bayangan",
    "trainerId" : "668f477b9381c23ad77d290f",
    "classCategory" : "Senam",
    "maxParticipant" : 50,
    "date" : "2023-01-01"
}

###
PUT http://localhost:5000/api/classes
Authorization: Bearer {{token}}